sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t pear25/docker-react .

script:
  - docker run -e CI=true pear25/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-611087197763"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id: "$AWS_SECRET_KEY"


